### ISSUE TITLE
Training data generation

### ISSUE THREAD

**Issue by BingCS** [XuyangBai/D3Feat#11]
Hi Xuyang,

Thanks for sharing your excellent work. I just want to learn some details about training data generation. For training point cloud fragments, did you select depth images in every 50 frames or fuse every 50 frames to generate ptclds?

Best ,
Bing

**Comment by XuyangBai** [comment]
Hi Bing,

Thanks for your interest. We follow the instruction of 3DMatch and fuse every 50 depth images to get one point cloud fragment for the training set. For the testing set, we just use the point clouds provided by 3DMatch.

Best,
Xuyang.

**Comment by BingCS** [comment]
Many thanks!
