### ISSUE TITLE
Could you publish a pytorch implementation ?

### ISSUE THREAD

**Issue by qxh123456789** [XuyangBai/D3Feat#13]
Dear XuyangBai,

Thank you for your great work! I have noticed that you have an implementation of KPConv. Have you done your pytorch implementation of D3Feat based on that ?

Best regards,
Xianghua Qu

**Comment by XuyangBai** [comment]
Hi Xianghua,

Thank for your interest. Yes, I have implemented a PyTorch version of D3Feat but need some time to polish the code. I will release it as soon as possible.

Best,
Xuyang

**Comment by qxh123456789** [comment]
Hey Xuyang,

Thanks for your time. Btw, have you looked at Hugues' (official) pytorch implementation of KPConv ? Did you use that for an implementation?

Best regards,
Xinghua

**Comment by XuyangBai** [comment]
Hi @qxh123456789 

Yes, I implemented the D3Feat PyTorch version based on the official KPConv-PyTorch with some modifications.

**Comment by qxh123456789** [comment]
Thank you @XuyangBai ,

I am looking forward to your work.

**Comment by XuyangBai** [comment]
Hi @qxh123456789  I just release the PyTorch code here https://github.com/XuyangBai/D3Feat.pytorch but current performance is a little bit lower than TensorFlow version. Please feel free to have a try.

**Comment by qxh123456789** [comment]
@XuyangBai Thank you for your efforts. I will try this later. 
Btw, may I ask about its current performance ? Did you save the registration recall and FMR result of your current implementation ?

**Comment by XuyangBai** [comment]
Hi @qxh123456789 the current implementation can achieve about 95.5% FMR.

**Comment by qxh123456789** [comment]
Hey @XuyangBai , 
Thank you for your time, I will try this, It sounds considerable, but what is the keypoints number you choose to test? Did your test your registratoin recall? As this version seems a little tricky for me to understand, I will be needing some time to check out the  differences between your current architecture and old version and other arguments setting. Will get back to you when I get the test results.

Best,
Xianghua Q

**Comment by XuyangBai** [comment]
Hi @qxh123456789  I mean the FMR is 95.5% over 5000 keypoints, and about 92.6% for 250 keypoints. Sorry I haven't evaluated the registration recall. Yes, the architectures and the arguments are slightly different from the TF version, probably they are not optimal and I just borrow some of them from KPConv-PyTorch or try some values, you may play with them to get better results.
