### ISSUE TITLE
Aligned or unaligned pts in Training and Testing datasets

### ISSUE THREAD

**Issue by BingCS** [XuyangBai/D3Feat#15]
Hi Xuyang,

I just noticed that you saved the aligned point cloud points as the training dataset but the testing dataset from 3DMatch are unaligned during the testing phase. May I confirm this with you? Many thanks.

Best,
Bing

**Comment by XuyangBai** [comment]
Hi @BingCS Exactly, I align the point cloud using gt transformation and add rotation translation augmentation for training (to achieve rotation invariant feature descriptors). But for the testset, I directly download it from [3DMatch](http://3dmatch.cs.princeton.edu/#geometric-registration-benchmark) for a fair comparison with other methods. 

Best,
Xuyang

**Comment by BingCS** [comment]
Thanks for your reply!
