### ISSUE TITLE
ERROR: pclkeypoint==0.0.1

### ISSUE THREAD

**Issue by fabiopoiesi** [XuyangBai/D3Feat#18]
Hi,

Installing the conda env I get this error:

ERROR: Could not find a version that satisfies the requirement pclkeypoint==0.0.1

Is this package necessary?

Cheers

**Comment by XuyangBai** [comment]
Hi @fabiopoiesi PCLKeypoint is only needed for detecting keypoints using the traditional algorithm (Harris 3D, SIFT 3D, ISS). It is not necessary for the registration task.

**Comment by fabiopoiesi** [comment]
Excellent! Thx
