### ISSUE TITLE
Figure2 metadata

### ISSUE THREAD

**Issue by ShengyuH** [XuyangBai/D3Feat#19]
hi Xuyang,

Do you mind sharing the metadata for Figure 2 in your paper?

best,
Shengyu

**Comment by XuyangBai** [comment]
Hi Shengyu,

The data you need is here.

[distance_threshold.txt](https://github.com/XuyangBai/D3Feat/files/5326529/distance_threshold.txt)
[inlier_threshold.txt](https://github.com/XuyangBai/D3Feat/files/5326530/inlier_threshold.txt)

Best,
Xuyang

**Comment by ShengyuH** [comment]
> Hi Shengyu,
> 
> The data you need is here.
> 
> [distance_threshold.txt](https://github.com/XuyangBai/D3Feat/files/5326529/distance_threshold.txt)
> [inlier_threshold.txt](https://github.com/XuyangBai/D3Feat/files/5326530/inlier_threshold.txt)
> 
> Best,
> Xuyang

Thank you for your prompt reply!
