### ISSUE TITLE
segmentation fault during training 3D match

### ISSUE THREAD

**Issue by tangbohu** [XuyangBai/D3Feat#2]
hello! Thanks for your sharing.

The code seems raise an error during runing the following code when I attempt to train on 3D Match. 
train_data = train_data.map(map_func=map_func, num_parallel_calls=self.num_threads) 

Looking forward to your kind reply!

**Comment by XuyangBai** [comment]
Hi, @tangbohu  Could you paste the error information here?

**Comment by tangbohu** [comment]
> Hi, @tangbohu Could you paste the error information here?

Thanks for your kind reply!


The error information is as follow:


Dataset Preparation
*******************

Preparing ply files
Num_train 3680

Preparing ply files
Num_val 1238
Initiating input pipelines
self.batch_limit: 32235.291046036124
WARNING: Logging before flag parsing goes to stderr.
W0419 10:41:07.728522 139672721119040 deprecation.py:323] From /home/user/.local/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py:494: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.

W0419 10:41:07.835422 139672721119040 deprecation.py:506] From /media/user/400a44dc-53f0-42c3-b7af-9a9931e73ec0/OriginWorkSpace/D3Feat/datasets/common.py:1308: calling reduce_min_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Segmentation fault (core dumped)



And I have debugged the code, and found that the code dumped at line 600 of the file dataset/common.py, namely the code "train_data = train_data.map(map_func=map_func, num_parallel_calls=self.num_threads)".

Thanks!

**Comment by XuyangBai** [comment]
Hi @tangbohu  I think you are using tensorflow2.0 or newer version? But there might be segmentation fault when using cpp custom op in `tf.data.Dataset.map` in tensorflow2.0, see this [issue](https://github.com/tensorflow/tensorflow/issues/29951). Maybe you can try tensorflow1.12.0 instead or try g++-4.8 to build the custom ops (I am not sure this can work or not). And my code is heavily built on [KPConv](https://github.com/HuguesTHOMAS/KPConv), and the author of KPConv might not test their code on tf 2.0.

**Comment by tangbohu** [comment]
Thanks for your kind reply! I believe I am using the same tensorflow library as you since I use the conda environment. Perhaps the version of g++ is not the same. Let me have a try. Thanks again for your quick response.

**Comment by tangbohu** [comment]
> Hi @tangbohu I think you are using tensorflow2.0 or newer version? But there might be segmentation fault when using cpp custom op in `tf.data.Dataset.map` in tensorflow2.0, see this [issue](https://github.com/tensorflow/tensorflow/issues/29951). Maybe you can try tensorflow1.12.0 instead or try g++-4.8 to build the custom ops (I am not sure this can work or not). And my code is heavily built on [KPConv](https://github.com/HuguesTHOMAS/KPConv), and the author of KPConv might not test their code on tf 2.0.

Thanks! It is caused by my upgrading of tensorflow from 1.12 to 1.14. The problem has been solved.

**Comment by zhouhao957** [comment]
@tangbohu    hello
I also have an error in this code
train_data = train_data.map(map_func=map_func, num_parallel_calls=self.num_threads)

error:
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
Are you like that? How did you solve it
