### ISSUE TITLE
RANSAC

### ISSUE THREAD

**Issue by ShengyuH** [XuyangBai/D3Feat#20]
hi Xuyang,

For Table 2 in your paper, may I ask which RANSAC do you use for FCGF features? Is that the same one as this: https://github.com/XuyangBai/D3Feat/blob/2213212a9bb1ecce4d1b6bf65edc8a84fa2b307f/geometric_registration/evaluate.py#L93?   The result here is much better than that reported in FCGF paper, I also tried this RANSAC, but can only get 83% recall. With Mutual check, I can get 86.3% recall, which is close to that reported in your work.

Best,
Shengyu

**Comment by XuyangBai** [comment]
Hi @ShengyuH Yes, I use the mutual check before RANSAC. Besides, the stop criteria, distance threshold will also affect the result of RANSAC. I remember that FCGF didn't release their setting for RANSAC when I submitted this paper so I use my setting to get the registration recall for different descriptors.

Best,
Xuyang.

**Comment by ShengyuH** [comment]
> Hi @ShengyuH Yes, I use the mutual check before RANSAC. Besides, the stop criteria, distance threshold will also affect the result of RANSAC. I remember that FCGF didn't release their setting for RANSAC when I submitted this paper so I use my setting to get the registration recall for different descriptors.
> 
> Best,
> Xuyang.

Thanks! Then this makes sense to me.
