### ISSUE TITLE
Question about training my own dataset

### ISSUE THREAD

**Issue by GitHubOKay** [XuyangBai/D3Feat#21]
Hi. I have one question about how to train my own dataset. 
I see the python code 'datasets/cal_overlap.py' you provided, and I am confused about the '**scene_list_{split}.txt**' and the '**{ind}.pose.npy**' files. It is will be helpful for me to understand, if you provides these files to me. 
Thanks very much. Have a nice day.

**Comment by XuyangBai** [comment]
Hi @GitHubOKay 3DMatch provided 54 scenes including 8 scenes for testing, the `scene_list_{split}.txt` indicates which scene is for training or testing, I derive it from [split.txt](https://vision.princeton.edu/projects/2016/3DMatch/downloads/rgbd-datasets/split.txt) from the 3DMatch website. And the `pose.npy` is the ground truth pose of fused point cloud fragments generated from the TSDF fusion step, you can find the code in my another [repo](https://github.com/XuyangBai/PPF-FoldNet/blob/master/script/fuse_fragments_3DMatch.py)

Best,
Xuyang.

**Comment by GitHubOKay** [comment]
Hi, @XuyangBai. Thanks for your reply. I will try.
