### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: tf_custom_ops/tf_neighbors.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Violetit** [XuyangBai/D3Feat#25]
Hi @XuyangBai 
I have completed training on the kitti dataset. After generating the descriptors and detection scores,  I ran the script `python evaluate_kitti_our.py D3Feat [timestr of the model]` to calculated the keypoint repeatability,  but an error occur:
```
Traceback (most recent call last):
  File "evaluate_kitti_our.py", line 9, in <module>
    from datasets.KITTI import KITTIDataset
  File "../datasets/KITTI.py", line 13, in <module>
    from datasets.common import Dataset
  File "../datasets/common.py", line 34, in <module>
    tf_neighbors_module = tf.load_op_library('tf_custom_ops/tf_neighbors.so')
  File "/home/ubuntu/.conda/envs/tia36/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: tf_custom_ops/tf_neighbors.so: cannot open shared object file: No such file or directory
```
However, no errors were reported during the entire training process of the kitti dataset, which should prove that my compilation is correct and the file is in the path `D3Feat/tf_custom_ops/tf_neighbors.so`. 

How can I help the `python evaluate_kitti_our.py D3Feat [timestr of the model]` to find the `D3Feat/tf_custom_ops/tf_neighbors.so` file? 
Could you please help me to solve this problem?

**Comment by XuyangBai** [comment]
Hi @Violetit If you run the script in the same folder with `tf_custom_ops/`, the program should be able to find it.

**Comment by Violetit** [comment]
> Hi @Violetit If you run the script in the same folder with `tf_custom_ops/`, the program should be able to find it.

Do you mean to put `python evaluate_kitti_our.py ` under the  `D3Feat/tf_custom_ops/` to run?

**Comment by XuyangBai** [comment]
You can run `python repeatability/evaluate_kitti_our.py` under the `D3Feat` folder.

**Comment by vvForedawn** [comment]
`$export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:(path to were libtensorflow_framework.so is)`
You can try it.
