### ISSUE TITLE
KITTI and 3DMatch, unalign or align?

### ISSUE THREAD

**Issue by ZhengdiYu** [XuyangBai/D3Feat#29]
Hey Xuyang,

I noticed that you use unaligned point clouds for KITTI training and the aligned point clouds are only used as backup_points for computing the false negative mask, but when it comes to 3DMatch, you use aligned point clouds.

In an other issue you pointed out that you aligned the point clouds in 3DMatch and add rotation translation augmentation to achieve rotation invariance. Could I ask why there is a difference between 3DMatch and KITTI?

Best,
Zhengdi

**Comment by XuyangBai** [comment]
Hi @ZhengdiYu it doesn't make much difference for using aligned or unaligned point cloud during training since we have rotation augmentation, you can also use unaligned point clouds for 3DMatch training. 

Best,
Xuyang.
