### ISSUE TITLE
Where to download the ply file ?

### ISSUE THREAD

**Issue by gmcalo** [XuyangBai/D3Feat#3]
In datasets/cal_overlap.py, it use the ply file instead of the rgbd picture which download on 3DMatch dataset. How to get the ply files?

**Comment by XuyangBai** [comment]
Hi @gmcalo  I follow the instructions of 3DMatch paper to fuse the RGBD image to get .ply file and its corresponding pose. You may find the code [here](https://github.com/XuyangBai/PPF-FoldNet/blob/master/script/fuse_fragments_3DMatch.py)
