### ISSUE TITLE
provide pytorch pre-trained model

### ISSUE THREAD

**Issue by fukexue** [XuyangBai/D3Feat#30]
Hello, sorry to disturb you, can you provide a model that has been pre-trained on pytorch?

**Comment by XuyangBai** [comment]
Hi @fukexue I have sent the Pytorch pre-trained model to you through email.

Best,
Xuyang.

**Comment by junha-l** [comment]
Hi, @XuyangBai 

Thanks for your awesome work
Do you mind if I ask to provide pytorch pretrained model?
