### ISSUE TITLE
Some questions about *.kpl

### ISSUE THREAD

**Issue by HOUYONGKUO** [XuyangBai/D3Feat#34]
Hello,
Thank you for your innovative work.
I see that the 3DMatch dataset seems to have to use "*.kpl" files.
Are the files "*.kpl" about keypoints？
Do I must need "*.kpl" files for training?
How do I get the "*.kpl" files using my dataset?
I do not understand how to train using my own dataset only with "*.ply" files.
Thanks.

**Comment by XuyangBai** [comment]
Hi, I think I do not have .kpl file. What I have is `.pkl` file which save the down-sampled point cloud and pre-computed correspondences for training. I got these two files using datasets/cal_overlap.py

https://github.com/XuyangBai/D3Feat/blob/9ca3f011dab41f51885c0836d7dd77ecf041bd37/datasets/ThreeDMatch.py#L108-L109

**Comment by MrZ19** [comment]
Hi, thank you for your sharing. However, I can not find the "scene_list_{split}.txt", where is it? Is it provided by original 3DMatch dataset? If possible, could you please share the detailed 3DMatch data preprocessing?

**Comment by XuyangBai** [comment]
Hi @MrZ19 The split files are provided by the original [3DMatch](http://3dmatch.cs.princeton.edu/#geometric-registration-benchmark). For data preprocessing, I follow the instructions of 3DMatch paper to fuse the RGBD image to get .ply file and its corresponding pose. You may find our code [here](https://github.com/XuyangBai/PPF-FoldNet/blob/master/script/fuse_fragments_3DMatch.py) or use the original implementation provided by [3DMatch](https://github.com/andyzeng/3dmatch-toolbox/tree/master/depth-fusion).

**Comment by HOUYONGKUO** [comment]
Hi，
Is “data_object_velodyne” used when training the KITTI dataset?

**Comment by XuyangBai** [comment]
No.

**Comment by HOUYONGKUO** [comment]
Hi，
there are multiple datasets in dataset "KITII". Which one will be used?
1.Download odometry data set (grayscale, 22 GB)
2.Download odometry data set (color, 65 GB)
3.Download odometry data set (velodyne laser data, 80 GB)
4.Download odometry data set (calibration files, 1 MB)
5.Download odometry ground truth poses (4 MB)
6.Download odometry development kit (1 MB)
Thanks.

**Comment by XuyangBai** [comment]
3,4,5 are needed.

**Comment by HOUYONGKUO** [comment]
Hi, when I used kitti's training results to match my own data, an error occurred:
```
Traceback (most recent call last):
  File "demo.py", line 207, in <module>
    model = KernelPointFCNN(dataset.flat_inputs, config)
  File "/media/vge/Public/PointRegistration/D3Feat/models/KPFCNN_model.py", line 119, in __init__
    self.anchor_inputs['trans'] = flat_inputs[ind]
IndexError: tuple index out of range
```

**Comment by HOUYONGKUO** [comment]
Hi, when I matched my data using pretrained model from KITTI, the error occured:
```
Traceback (most recent call last):
  File "demo.py", line 207, in <module>
    model = KernelPointFCNN(dataset.flat_inputs, config)
  File "/media/vge/Public/PointRegistration/D3Feat/models/KPFCNN_model.py", line 120, in __init__
    self.object_inds = self.anchor_inputs['object_inds']
KeyError: 'object_inds'
```
What is the 'object_inds'?

**Comment by HOUYONGKUO** [comment]
Hi，I did not find how to set the batch size.
Thanks. I would be grateful if you could help me figure this out.

**Comment by XuyangBai** [comment]
Currently this codebase only support batch size equals 1

**Comment by HOUYONGKUO** [comment]
Hello, I noticed that your method does not need to load an additional corresponding ‘keypoint.txt’ file when matching (such as 3DSmoothNet/TEASER++, which are required), which makes it more convenient to use our own data. How to achieve it？

**Comment by HOUYONGKUO** [comment]
Thanks! If using my own data for registration, which path will the keypoints data be stored?

**Comment by XuyangBai** [comment]
you can see the following part

https://github.com/XuyangBai/D3Feat/blob/9ca3f011dab41f51885c0836d7dd77ecf041bd37/utils/tester.py#L185-L187

**Comment by HOUYONGKUO** [comment]
Thanks! But I find that the files in these paths are all about the descriptor, keypoint and score of the 3DMatch dataset. There aren't relevant files about my own test data for registration.

**Comment by XuyangBai** [comment]
You can change the path to that of your dataset. D3Feat only needs `.ply` as input, and generates per-point descriptor, detection score. You can see https://github.com/XuyangBai/D3Feat/blob/master/demo_registration.py as an example.
