### ISSUE TITLE
How can I obtain the original 3DMatch dataset

### ISSUE THREAD

**Issue by MrZ19** [XuyangBai/D3Feat#35]
Hi, your /datasets/cal_overlap.py, which handle the original 3DMatch dataset, could you please share the this original 3DMatch dataset, or provide a download link, I can not find the "scene_list_{split}.txt" file, is it provided officially as "http://vision.princeton.edu/projects/2016/3DMatch/downloads/rgbd-datasets/download.sh" and 
"http://vision.princeton.edu/projects/2016/3DMatch/downloads/rgbd-datasets/split.txt" in 
"http://3dmatch.cs.princeton.edu/#geometric-registration-benchmark"?
![image](https://user-images.githubusercontent.com/50171848/124274814-4da0b880-db74-11eb-9ead-54950b98e9de.png)

**Comment by XuyangBai** [comment]
Yes, all the origin RGB-D, poses, and split files are provided by 3DMatch http://3dmatch.cs.princeton.edu/#geometric-registration-benchmark
