### ISSUE TITLE
A question about downsampling of ETH DataSet

### ISSUE THREAD

**Issue by Hui-design** [XuyangBai/D3Feat#36]
Hi,
Thanks for your amazing work.
I come across a problem and want to ask you for help. When you preprocessed the ETH dataset, you used a downsample_size of 0.0625. But unfortunately, when we tested it, our GUP (22945MiB) was out of memory. After debugging, we found that the number of points after 0.0625 sampling was too large. And we also found that the point cloud samples of different frames are The number of points is uneven. How did you solve it?

**Comment by XuyangBai** [comment]
Hi, the experiments on the ETH dataset were conducted on my 2080Ti GPU, so it should not OOM on your GPU. Did you use the ply provided by [3DSmoothNet](https://github.com/zgojcic/3DSmoothNet)? Could you double-check the data and the downsampling step?

**Comment by Hui-design** [comment]
Thank you very much for your reply.
I have re-checked the data set and downsampling process, and I think there is nothing wrong.
In fact, I did not run the tf version of the code, I just came here to take a look at downsample_size.
The pytorch version of the code is what I am reading, but there is no test code for ETH there, so I modified and tested ETH based on "test.py" and "ThreeDMath.py",detaily for the scenelist and filepath, but OOM appeared.
 Did I miss other preprocessing steps?

**Comment by XuyangBai** [comment]
Could you leave an email address? I can send you the pytorch eth testing code.

**Comment by Hui-design** [comment]
2225705604@qq.cm
Thank you very much !

**Comment by Hui-design** [comment]
The email should be 2225705604@qq.com
Sorry, I sent the wrong email address. . . I'm sorry for bothering you so late, you can post it tomorrow
