### ISSUE TITLE
File size limit of the data

### ISSUE THREAD

**Issue by houyongkuo** [XuyangBai/D3Feat#38]
Hi，How do you use open3d to visualize the kitti dataset, do you convert it to .ply format or use .bin directly? In addition, are there any tests for the file size limit of the data used or the number of point clouds?Thanks.

**Comment by XuyangBai** [comment]
I use ply format. You can see `demo.py` for some examples. For the second question, you mean the size of single point cloud or the number of point cloud pairs?

**Comment by houyongkuo** [comment]
Thanks.
Single point cloud.

**Comment by XuyangBai** [comment]
I haven't tested the maximum number of points the network can process for single point cloud. You can do voxel-downsampling to avoid the meaningless dense areas and control the number of points. Also It should depends on your GPU.

**Comment by HOUYONGKUO** [comment]
Thanks. What is the size of the single point cloud file of figure 8 and 9 at the end of the paper？

**Comment by houyongkuo** [comment]
Thanks. How to set the parameters to achieve the display in open3d like Figure 8 and Figure 9 in the paper？

**Comment by XuyangBai** [comment]
The point cloud is visualized simply using `draw_geometries` and color decided by `x` or `y` value. The red dot is visualized by creating a mesh sphere (`create_mesh_sphere` function) and paint it as red.

**Comment by houyongkuo** [comment]
Thanks, but now, the outdoor point cloud I am using is relatively large, about 10 million points, and the voxel can be calculated by setting it to about 0.8, but open3d seems to determine the point cloud radius based on the voxel size (I didn’t find how to set the point cloud radius), so every point cloud in open3d window is very large, it looks like a group of cubes.  Happy Mid-Autumn Festival!

**Comment by XuyangBai** [comment]
Hi, Happy Mid-Autumn Festival :) 

I remember for the visualization window appeared after you call`draw_geometries`, you can use `+` or `-` to change the size of each point.  You can press `H` inside the window to see the instruction.

**Comment by houyongkuo** [comment]
I found that D3Feat is not suitable for complex outdoor point clouds, including trees, street lights, flower beds, etc. Even if the sampling is down to about 500,000 points, the correspondence cannot be found.

**Comment by XuyangBai** [comment]
It is possible. D3Feat is only trained on indoor scenes and needs some hyperparameter adjustment for outdoor scenes, as what we do when evaluating the generalization ability on ETH. Even though the performance is still not as good as patch-based descriptors, you may try https://github.com/QingyongHu/SpinNet or https://github.com/HpWang-whu/YOHO.
