### ISSUE TITLE
Why i cannot get the first dimension of the features' shape? 

### ISSUE THREAD

**Issue by BiaoBiaoLi** [XuyangBai/D3Feat#48]
Thanks your work!
In the D3Feat.py, i print the shape,
```
def assemble_FCNN_blocks(inputs, config, dropout_prob):
    # First get features from CNN  
    F = assemble_CNN_blocks(inputs, config, dropout_prob)
    features = F[-1]
    for f in F:
        print("the feature shape ", f.shape)
```
but get the below:
![image](https://user-images.githubusercontent.com/44672683/147432454-7b0cd852-517c-45e7-b01f-d913c8c99a2d.png)
but i see the dimension of the features in paper are : 64 128 256 512 1024

**Comment by XuyangBai** [comment]
it is the feature of TensorFlow. you can use `tf.Print` to printout the real value of `features`

**Comment by BiaoBiaoLi** [comment]
Thanks，i get it
