### ISSUE TITLE
Error in calculating overlap

### ISSUE THREAD

**Issue by houyongkuo** [XuyangBai/D3Feat#51]
Hello, I have a problem when I use your cal_overlap.py file to get a point cloud with a degree of overlap higher than 30%. I only get a file with a size of 5b. It feels like I have not read the ply point cloud or fragments. Thanks.

> Total 7 scenes, 0 point cloud fragments.
> Load pts file from ~/data/3DMatch/raw_data/cal_over/
> Reload overlap info from ~/data/3DMatch/raw_data/cal_over/3DMatch_train_0.300_overlap.pkl
> Reload keypts info from ~/data/3DMatch/raw_data/cal_over/3DMatch_train_0.300_keypts.pkl
> Begin processing scene sun3d-home_at-home_at_scan1_2013_jan_1
> Finish sun3d-home_at-home_at_scan1_2013_jan_1, Done in 0.0s
> Begin processing scene sun3d-home_md-home_md_scan9_2012_sep_30
> Finish sun3d-home_md-home_md_scan9_2012_sep_30, Done in 0.0s
> Begin processing scene sun3d-hotel_uc-scan3
> Finish sun3d-hotel_uc-scan3, Done in 0.0s
> Begin processing scene sun3d-hotel_umd-maryland_hotel1
> Finish sun3d-hotel_umd-maryland_hotel1, Done in 0.0s
> Begin processing scene sun3d-hotel_umd-maryland_hotel3
> Finish sun3d-hotel_umd-maryland_hotel3, Done in 0.0s
> Begin processing scene sun3d-mit_76_studyroom-76-1studyroom2
> Finish sun3d-mit_76_studyroom-76-1studyroom2, Done in 0.0s
> Begin processing scene sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika
> Finish sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, Done in 0.0s

**Comment by houyongkuo** [comment]
I carefully studied the file that should be missing the beginning of seq, what is this? It looks like a sequence file.

**Comment by houyongkuo** [comment]
The pose.npy file should be missing, how can I get it? thanks

**Comment by houyongkuo** [comment]
Hello, I have solved this problem by downloading the pose file in txt format from the official website and converting it into a matrix. But I don't quite understand why this rotation matrix is being multiplied. Thanks.

**Comment by sysu17363087** [comment]
> I carefully studied the file that should be missing the beginning of seq, what is this? It looks like a sequence file.

Hi, I met the same problem. How did you solve it? As so far, I suppose the seq_ is just the naming rule of training dataset folder.
