### ISSUE TITLE
error when run test_kitti

### ISSUE THREAD

**Issue by tracykim** [XuyangBai/D3Feat#8]
hi,when i run test_kitti.py use pretrained model your provided, there is an error in  
/utils/tester.py, line 326, in test_kitti 
T_gth = inputs['trans']
KeyError: 'trans'

i have checked inputs do not have a key 'trans', so how  to solve it, thank you.

**Comment by XuyangBai** [comment]
Hi, @tracykim  I just tried the code, and the code went well on my server. So could you check it again? The `trans` will be saved at this [line](https://github.com/XuyangBai/D3Feat/blob/3577482efbc5154affcd734e16b0d10a73560e37/utils/tester.py#L318).

**Comment by tracykim** [comment]
hi,thanks for your reply in time, i can save npz,what i means is this [line](https://github.com/XuyangBai/D3Feat/blob/3577482efbc5154affcd734e16b0d10a73560e37/utils/tester.py#L326)

**Comment by tracykim** [comment]
hi,thanks for your reply in time, i can save npz,what i means is this [line](https://github.com/XuyangBai/D3Feat/blob/3577482efbc5154affcd734e16b0d10a73560e37/utils/tester.py#L326)

**Comment by XuyangBai** [comment]
Sorry I misunderstood your question, the ground truth transformation was saved in `model.anchor_inputs` in [here](https://github.com/XuyangBai/D3Feat/blob/3577482efbc5154affcd734e16b0d10a73560e37/models/KPFCNN_model.py#L119) so there should be a key named `trans` for KITTI, did you changed the name of the dataset? It should be working if you use the default `test_kitti.py`

Hope that helps.

**Comment by tracykim** [comment]
hi,you got it,thanks a lot!
